import "./globals.css";
import { inter } from "./font.js";
import Navbar from "@/components/Navbar/Navbar.js";
import Footer from "@/components/Footer.js";

export const metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container`}>
        <Navbar />
        {children} <Footer />
      </body>
    </html>
  );
}
